In [2]:
import pandas as pd

In [5]:
infile = 

df1 = pd.read_csv(infile1)
df2 = pd.read_csv(infile2)

/usr/local/lib/python2.7/dist-packages/pandas/io/parsers.py:1170: DtypeWarning: Columns (3) have mixed types. Specify dtype option on import or set low_memory=False.
  data = self._reader.read(nrows)

In [63]:
print df1.head(1)
print df1.columns
df1_red = df1[['line_id','line_desc','DataValue','GeoFips','GeoName','TimePeriod','CL_UNIT','UNIT_MULT']]
print df1_red.columns

   Unnamed: 0               CL_UNIT    Code DataValue  GeoFips  \
0           0  thousands of dollars  CA5-10    443561    10180

                                       GeoName NoteRef  TimePeriod  UNIT_MULT  \
0  Abilene, TX (Metropolitan Statistical Area)     NaN        1970          3

   line_id              line_desc
0       10  [CA5] Personal income
Index([u'Unnamed: 0', u'CL_UNIT', u'Code', u'DataValue', u'GeoFips',
       u'GeoName', u'NoteRef', u'TimePeriod', u'UNIT_MULT', u'line_id',
       u'line_desc'],
      dtype='object')
Index([u'line_id', u'line_desc', u'DataValue', u'GeoFips', u'GeoName',
       u'TimePeriod', u'CL_UNIT', u'UNIT_MULT'],
      dtype='object')

In [64]:
df1_reindex = df1_red.set_index(['line_id','line_desc','GeoFips','GeoName','CL_UNIT','UNIT_MULT','TimePeriod'])

print len(df1_reindex)
print df1_reindex.head(10)
print '---------------------'

df1_unstack = df1_reindex.unstack()
print df1_unstack.head(10)
print '---------------------'

df1_unstack.columns = df1_unstack.columns.get_level_values(1).values
print df1_unstack.head(10)
print '---------------------'

df1_unstack = df1_unstack.reset_index()

df1_unstack.head(5)

1377696
                                                                                                                            DataValue
line_id line_desc             GeoFips GeoName                                     CL_UNIT              UNIT_MULT TimePeriod
10      [CA5] Personal income 10180   Abilene, TX (Metropolitan Statistical Area) thousands of dollars 3         1970          443561
                                                                                                                 1997         3329032
                                                                                                                 1998         3490073
                                                                                                                 1974          653309
                                                                                                                 1975          767316
                                                                                                                 1987         2080216
                                                                                                                 1988         2172339
                                                                                                                 1976          847447
                                                                                                                 1977          920462
                                                                                                                 1989         2259072
---------------------
                                                                                                                        DataValue  \
TimePeriod                                                                                                                   1969
line_id line_desc             GeoFips GeoName                                            CL_UNIT              UNIT_MULT
10      [CA5] Personal income 10180   Abilene, TX (Metropolitan Statistical Area)        thousands of dollars 3            395971
                              10420   Akron, OH (Metropolitan Statistical Area)          thousands of dollars 3           2721371
                              10500   Albany, GA (Metropolitan Statistical Area)         thousands of dollars 3            327783
                              10540   Albany, OR (Metropolitan Statistical Area)         thousands of dollars 3            223860
                              10580   Albany-Schenectady-Troy, NY (Metropolitan Stati... thousands of dollars 3           2975658
                              10740   Albuquerque, NM (Metropolitan Statistical Area)    thousands of dollars 3           1240462
                              10780   Alexandria, LA (Metropolitan Statistical Area)     thousands of dollars 3            367778
                              10900   Allentown-Bethlehem-Easton, PA-NJ (Metropolitan... thousands of dollars 3           2278974
                              11020   Altoona, PA (Metropolitan Statistical Area)        thousands of dollars 3            431089
                              11100   Amarillo, TX (Metropolitan Statistical Area)       thousands of dollars 3            553763

                                                                                                                                  \
TimePeriod                                                                                                                  1970
line_id line_desc             GeoFips GeoName                                            CL_UNIT              UNIT_MULT
10      [CA5] Personal income 10180   Abilene, TX (Metropolitan Statistical Area)        thousands of dollars 3           443561
                              10420   Akron, OH (Metropolitan Statistical Area)          thousands of dollars 3          2837126
                              10500   Albany, GA (Metropolitan Statistical Area)         thousands of dollars 3           379876
                              10540   Albany, OR (Metropolitan Statistical Area)         thousands of dollars 3           241272
                              10580   Albany-Schenectady-Troy, NY (Metropolitan Stati... thousands of dollars 3          3307720
                              10740   Albuquerque, NM (Metropolitan Statistical Area)    thousands of dollars 3          1406626
                              10780   Alexandria, LA (Metropolitan Statistical Area)     thousands of dollars 3           395471
                              10900   Allentown-Bethlehem-Easton, PA-NJ (Metropolitan... thousands of dollars 3          2469997
                              11020   Altoona, PA (Metropolitan Statistical Area)        thousands of dollars 3           470010
                              11100   Amarillo, TX (Metropolitan Statistical Area)       thousands of dollars 3           600922

                                                                                                                                  \
TimePeriod                                                                                                                  1971
line_id line_desc             GeoFips GeoName                                            CL_UNIT              UNIT_MULT
10      [CA5] Personal income 10180   Abilene, TX (Metropolitan Statistical Area)        thousands of dollars 3           474234
                              10420   Akron, OH (Metropolitan Statistical Area)          thousands of dollars 3          2987986
                              10500   Albany, GA (Metropolitan Statistical Area)         thousands of dollars 3           433462
                              10540   Albany, OR (Metropolitan Statistical Area)         thousands of dollars 3           267093
                              10580   Albany-Schenectady-Troy, NY (Metropolitan Stati... thousands of dollars 3          3656765
                              10740   Albuquerque, NM (Metropolitan Statistical Area)    thousands of dollars 3          1588949
                              10780   Alexandria, LA (Metropolitan Statistical Area)     thousands of dollars 3           449222
                              10900   Allentown-Bethlehem-Easton, PA-NJ (Metropolitan... thousands of dollars 3          2632989
                              11020   Altoona, PA (Metropolitan Statistical Area)        thousands of dollars 3           498833
                              11100   Amarillo, TX (Metropolitan Statistical Area)       thousands of dollars 3           654713

                                                                                                                                  \
TimePeriod                                                                                                                  1972
line_id line_desc             GeoFips GeoName                                            CL_UNIT              UNIT_MULT
10      [CA5] Personal income 10180   Abilene, TX (Metropolitan Statistical Area)        thousands of dollars 3           539294
                              10420   Akron, OH (Metropolitan Statistical Area)          thousands of dollars 3          3260687
                              10500   Albany, GA (Metropolitan Statistical Area)         thousands of dollars 3           489268
                              10540   Albany, OR (Metropolitan Statistical Area)         thousands of dollars 3           296402
                              10580   Albany-Schenectady-Troy, NY (Metropolitan Stati... thousands of dollars 3          3934076
                              10740   Albuquerque, NM (Metropolitan Statistical Area)    thousands of dollars 3          1823000
                              10780   Alexandria, LA (Metropolitan Statistical Area)     thousands of dollars 3           490112
                              10900   Allentown-Bethlehem-Easton, PA-NJ (Metropolitan... thousands of dollars 3          2920001
                              11020   Altoona, PA (Metropolitan Statistical Area)        thousands of dollars 3           535230
                              11100   Amarillo, TX (Metropolitan Statistical Area)       thousands of dollars 3           699528

                                                                                                                                  \
TimePeriod                                                                                                                  1973
line_id line_desc             GeoFips GeoName                                            CL_UNIT              UNIT_MULT
10      [CA5] Personal income 10180   Abilene, TX (Metropolitan Statistical Area)        thousands of dollars 3           579305
                              10420   Akron, OH (Metropolitan Statistical Area)          thousands of dollars 3          3561357
                              10500   Albany, GA (Metropolitan Statistical Area)         thousands of dollars 3           566336
                              10540   Albany, OR (Metropolitan Statistical Area)         thousands of dollars 3           343431
                              10580   Albany-Schenectady-Troy, NY (Metropolitan Stati... thousands of dollars 3          4225636
                              10740   Albuquerque, NM (Metropolitan Statistical Area)    thousands of dollars 3          2030765
                              10780   Alexandria, LA (Metropolitan Statistical Area)     thousands of dollars 3           544666
                              10900   Allentown-Bethlehem-Easton, PA-NJ (Metropolitan... thousands of dollars 3          3288541
                              11020   Altoona, PA (Metropolitan Statistical Area)        thousands of dollars 3           588697
                              11100   Amarillo, TX (Metropolitan Statistical Area)       thousands of dollars 3           816412

                                                                                                                                  \
TimePeriod                                                                                                                  1974
line_id line_desc             GeoFips GeoName                                            CL_UNIT              UNIT_MULT
10      [CA5] Personal income 10180   Abilene, TX (Metropolitan Statistical Area)        thousands of dollars 3           653309
                              10420   Akron, OH (Metropolitan Statistical Area)          thousands of dollars 3          3875437
                              10500   Albany, GA (Metropolitan Statistical Area)         thousands of dollars 3           587184
                              10540   Albany, OR (Metropolitan Statistical Area)         thousands of dollars 3           393454
                              10580   Albany-Schenectady-Troy, NY (Metropolitan Stati... thousands of dollars 3          4580685
                              10740   Albuquerque, NM (Metropolitan Statistical Area)    thousands of dollars 3          2274156
                              10780   Alexandria, LA (Metropolitan Statistical Area)     thousands of dollars 3           590985
                              10900   Allentown-Bethlehem-Easton, PA-NJ (Metropolitan... thousands of dollars 3          3691259
                              11020   Altoona, PA (Metropolitan Statistical Area)        thousands of dollars 3           646029
                              11100   Amarillo, TX (Metropolitan Statistical Area)       thousands of dollars 3           888068

                                                                                                                                  \
TimePeriod                                                                                                                  1975
line_id line_desc             GeoFips GeoName                                            CL_UNIT              UNIT_MULT
10      [CA5] Personal income 10180   Abilene, TX (Metropolitan Statistical Area)        thousands of dollars 3           767316
                              10420   Akron, OH (Metropolitan Statistical Area)          thousands of dollars 3          4109115
                              10500   Albany, GA (Metropolitan Statistical Area)         thousands of dollars 3           615977
                              10540   Albany, OR (Metropolitan Statistical Area)         thousands of dollars 3           426744
                              10580   Albany-Schenectady-Troy, NY (Metropolitan Stati... thousands of dollars 3          4955323
                              10740   Albuquerque, NM (Metropolitan Statistical Area)    thousands of dollars 3          2565764
                              10780   Alexandria, LA (Metropolitan Statistical Area)     thousands of dollars 3           660141
                              10900   Allentown-Bethlehem-Easton, PA-NJ (Metropolitan... thousands of dollars 3          4057618
                              11020   Altoona, PA (Metropolitan Statistical Area)        thousands of dollars 3           711663
                              11100   Amarillo, TX (Metropolitan Statistical Area)       thousands of dollars 3          1094463

                                                                                                                                  \
TimePeriod                                                                                                                  1976
line_id line_desc             GeoFips GeoName                                            CL_UNIT              UNIT_MULT
10      [CA5] Personal income 10180   Abilene, TX (Metropolitan Statistical Area)        thousands of dollars 3           847447
                              10420   Akron, OH (Metropolitan Statistical Area)          thousands of dollars 3          4413597
                              10500   Albany, GA (Metropolitan Statistical Area)         thousands of dollars 3           682030
                              10540   Albany, OR (Metropolitan Statistical Area)         thousands of dollars 3           493367
                              10580   Albany-Schenectady-Troy, NY (Metropolitan Stati... thousands of dollars 3          5285550
                              10740   Albuquerque, NM (Metropolitan Statistical Area)    thousands of dollars 3          2904823
                              10780   Alexandria, LA (Metropolitan Statistical Area)     thousands of dollars 3           741936
                              10900   Allentown-Bethlehem-Easton, PA-NJ (Metropolitan... thousands of dollars 3          4413255
                              11020   Altoona, PA (Metropolitan Statistical Area)        thousands of dollars 3           793238
                              11100   Amarillo, TX (Metropolitan Statistical Area)       thousands of dollars 3          1197532

                                                                                                                                  \
TimePeriod                                                                                                                  1977
line_id line_desc             GeoFips GeoName                                            CL_UNIT              UNIT_MULT
10      [CA5] Personal income 10180   Abilene, TX (Metropolitan Statistical Area)        thousands of dollars 3           920462
                              10420   Akron, OH (Metropolitan Statistical Area)          thousands of dollars 3          4932337
                              10500   Albany, GA (Metropolitan Statistical Area)         thousands of dollars 3           742458
                              10540   Albany, OR (Metropolitan Statistical Area)         thousands of dollars 3           558266
                              10580   Albany-Schenectady-Troy, NY (Metropolitan Stati... thousands of dollars 3          5714669
                              10740   Albuquerque, NM (Metropolitan Statistical Area)    thousands of dollars 3          3254105
                              10780   Alexandria, LA (Metropolitan Statistical Area)     thousands of dollars 3           811788
                              10900   Allentown-Bethlehem-Easton, PA-NJ (Metropolitan... thousands of dollars 3          4879189
                              11020   Altoona, PA (Metropolitan Statistical Area)        thousands of dollars 3           875052
                              11100   Amarillo, TX (Metropolitan Statistical Area)       thousands of dollars 3          1321402

                                                                                                                                  \
TimePeriod                                                                                                                  1978
line_id line_desc             GeoFips GeoName                                            CL_UNIT              UNIT_MULT
10      [CA5] Personal income 10180   Abilene, TX (Metropolitan Statistical Area)        thousands of dollars 3          1057503
                              10420   Akron, OH (Metropolitan Statistical Area)          thousands of dollars 3          5460620
                              10500   Albany, GA (Metropolitan Statistical Area)         thousands of dollars 3           857866
                              10540   Albany, OR (Metropolitan Statistical Area)         thousands of dollars 3           622628
                              10580   Albany-Schenectady-Troy, NY (Metropolitan Stati... thousands of dollars 3          6254271
                              10740   Albuquerque, NM (Metropolitan Statistical Area)    thousands of dollars 3          3774231
                              10780   Alexandria, LA (Metropolitan Statistical Area)     thousands of dollars 3           922268
                              10900   Allentown-Bethlehem-Easton, PA-NJ (Metropolitan... thousands of dollars 3          5426312
                              11020   Altoona, PA (Metropolitan Statistical Area)        thousands of dollars 3           963836
                              11100   Amarillo, TX (Metropolitan Statistical Area)       thousands of dollars 3          1498223

                                                                                                                           ...     \
TimePeriod                                                                                                                 ...
line_id line_desc             GeoFips GeoName                                            CL_UNIT              UNIT_MULT    ...
10      [CA5] Personal income 10180   Abilene, TX (Metropolitan Statistical Area)        thousands of dollars 3            ...
                              10420   Akron, OH (Metropolitan Statistical Area)          thousands of dollars 3            ...
                              10500   Albany, GA (Metropolitan Statistical Area)         thousands of dollars 3            ...
                              10540   Albany, OR (Metropolitan Statistical Area)         thousands of dollars 3            ...
                              10580   Albany-Schenectady-Troy, NY (Metropolitan Stati... thousands of dollars 3            ...
                              10740   Albuquerque, NM (Metropolitan Statistical Area)    thousands of dollars 3            ...
                              10780   Alexandria, LA (Metropolitan Statistical Area)     thousands of dollars 3            ...
                              10900   Allentown-Bethlehem-Easton, PA-NJ (Metropolitan... thousands of dollars 3            ...
                              11020   Altoona, PA (Metropolitan Statistical Area)        thousands of dollars 3            ...

,line_id,line_desc,GeoFips,GeoName,CL_UNIT,UNIT_MULT,1969,1970,1971,1972,...,1991,1992,1993,1994,1995,1996,1997,1998,1999,2000
0,10,[CA5] Personal income,10180,"Abilene, TX (Metropolitan Statistical Area)",thousands of dollars,3,395971,443561,474234,539294,...,2376433,2538036,2663665,2722081,2918059,3109606,3329032,3490073,3639311,3741391
1,10,[CA5] Personal income,10420,"Akron, OH (Metropolitan Statistical Area)",thousands of dollars,3,2721371,2837126,2987986,3260687,...,12661425,13555125,14168305,15042354,15953574,16789127,17766575,18896648,19577386,20759334
2,10,[CA5] Personal income,10500,"Albany, GA (Metropolitan Statistical Area)",thousands of dollars,3,327783,379876,433462,489268,...,2266999,2386012,2499555,2737388,2889006,3068305,3163081,3293190,3386466,3527098
3,10,[CA5] Personal income,10540,"Albany, OR (Metropolitan Statistical Area)",thousands of dollars,3,223860,241272,267093,296402,...,1487651,1583635,1692484,1798641,1919740,2093495,2168808,2244474,2310004,2412870
4,10,[CA5] Personal income,10580,"Albany-Schenectady-Troy, NY (Metropolitan Stat...",thousands of dollars,3,2975658,3307720,3656765,3934076,...,17749791,18836591,19442450,20166188,20800976,21474704,22679387,23691537,24761331,26423368

In [65]:
df1_unstack.to_csv('test.txt')